


setTimeout(()=>{
  var selectedValue = "legalStatus";
  updateMarkers(selectedValue);
},500);
// fetch('https://omarthisside.github.io/esyacentre')
// .then((response) => response.json())
// .then((json) => countryData = json);

  var countryData=[  
    {
      "countryName": "Argentina",
      "legalStatus": ["Legal",""],
      "classification":["No","The Central Bank defined digital assets as a digital representation of value or rights that are transferred and stored electronically. They are not legal tender. Further, digital assets cannot be classified as securities as they are not registered pursuant to the Securities and Exchange Commission."],
      "licensing": ["No","There is currently no licensing regime for non-financial institutions offering digital asset related services. A license may be required if the assets offered qualify as securities"],
      "corporateGovernance": ["No","There are no corporate governance requirements that apply specifically to digital asset service providers (DASPs)"],
      "riskManagement": ["No","There are no risk management principles that apply specifically to DASPs"],
      "taxation":["Yes","For resident individuals, gains derived from the disposal of digital assets is subject to an income tax of 15%<br/>Resident legal entities are taxed 25-35% on gains from disposing of digital assets<br/>Non-residents who obtain gains from disposing digital assets and there is an Argentine source of income are taxed at a rate of 15%<br/>Residents are taxed on the assets they own at a rate that ranges from 0.50% to 2.25% depending on the value of the assets and where it is located.<br/>A check tax of 0.6% on all transactions involving digital has also been imposed <br/>No Value Added Tax is imposed on digital For resident individuals, gains derived from the disposal of digital assets is subject to an income tax of 15%<br/>Resident legal entities are taxed 25-35% on gains from disposing of digital assets<br/>Non-residents who obtain gains from disposing digital assets and there is an Argentine source of income are taxed at a rate of 15%<br/>Residents are taxed on the assets they own at a rate that ranges from 0.50% to 2.25% depending on the value of the assets and where it is located.<br/>A check tax of 0.6% on all transactions involving digital has also been imposed <br/>No Value Added Tax is imposed on digital assets."],
      "capitalControls":["No","Argentina has a strong capital controls regime, the provisions of which have not been explicitly extended to digital assets for the moment."],
      "amlCft":["Partial","Argentina issued UIF Resolution 300 in 2014 to create reporting obligations for financial institutions on 'operations performed with virtual coins'. <br/>General Resolution AFIP 4614/2019 requires giving information to the Federal<br/>Administration of Public Revenues (AFIP) on transactions that include virtual accounts, digital wallets and service providers.<br/>The AFIP uses this information to monitor the development of the digital asset ecosystem as well as to collect taxes on these transactions.<br/>Argentina may revise its anti-money laundering law to include a registry for DASPs."],
      "grievanceRedressal":["Partial - General Legislation", "Argentina has a robust consumer protection regime under the Constitution, Civil Code and standalone legislation. Whether DASPs are covered under these remains an open question in the absence of specific guidance"],
      "dataProtection":["Partial - General Legislation","There are currently no specific data protection or information security practices that specifically apply to DASPs in Argentina even though the country has a data protection regime in place"],
      "advertisingRegulations":["No","No specific regulations or guidelines currently limit digital asset-related advertising. However, the head of Argentina's Capital Markets Authority has noted the need to regulate ads put out by DASPs"],
      "consumerAwareness":["Proposed", "The purpose of advertisement regulation is to educate potential users of digital assets and to protect investors from falling into fake and ponzi schemes based on digital assets."],
      "investorProtection":["No","Digital asset holdings are not covered by deposit insurance applicable to other financial instruments "],
      "restrictions":["Yes","Argentinian banks are prohibited from directly facilitating the purchase and sale of digital assets. However, domestic cryptocurrency exchanges are still operational"],

      "lat": "38.4161",
      "lang": "63.6167"
    },
    {
      "countryName": "Australia",
      "legalStatus": ["Legal","While there is currently no specific regulation for digital assets in Australia, they may be regulated as collective investment schemes, securities or ETPs governed under the Corporations Act 2001 and the Australian Securities and Investments Commission Act depending on their rights and features. <br/>A proposed framework that comprehensively regulates digital assets is also being worked on"],
      "classification":["Yes","Digital assets may be classified as different financial products, including exchange-traded products and securities, depending on their functionality and purpose.<br/>The Australian Securities and Investments Commission specifies when digital assets may be considered financial products <br/>The Australian Treasury has also released a consultation paper on token mapping, which is the first step in creating a holistic regulatory framework for digital assets. The token mapping exercise classifies digital assets as under: <br/>1) Intermediated token systems - where an intermediary/agent is involved in fulfilling contractual obligations related to tokens. They form the link between digital assets and the 'real world.' <br/>1a) Crypto asset services - a token system that accepts crypto tokens as part of performing a service (fiat on-ramps, custody, lending and borrowing, etc.) <br/>1b) Intermediated crypto assets - link between the crypto token and token system is created by legal or other arrangements. This would include cases where the value of a crypto asset is linked to real-world assets or assets (tokenised securities, stablecoins, etc.) <br/>2) Public token systems - these do not involve an intermediary for the performance of a function related to crypto assets. Instead, the performance is ensured by the crypto network directly. Parties transacting over public token systems may not necessarily know each other <br/>2a) Network tokens - tokens created by the network to reward specific participants (for eg. Bitcoin, Ether etc.) <br/>2b) Public smart contracts - non-intermedaited smart contracts hosted on public token systems that usually fulfil one of three objectives: i) interoperability (bridges and wrapped tokens)  ii) economic (automated market makers and DeFi protocols) iii) coordination (collective investment DAOs) <br/>The consultation paper maps these token categories against definitions of financial instruments in Australia. It is an exploratory exercise to form the basis for future regulation, including licensing and custody."],
      "licensing": ["Yes","All 'digital currency' exchanges must register with the AUSTRAC, which is Australia's anti-money laundering watchdog. <br/>Additionally, any digital asset service provider that lists or issues currencies classified as financial products requires an 'Australian Financial Services' AFS license <br/>A consultation on creating a licensing and custody requirement framework for 'crypto asset secondary service providers' (CASSPs) was completed by the Treasury in May 2022. Further developments in this regard are awaited "],
      "corporateGovernance": ["Partial","There are currently no corporate governance requirements for DASPs in Australia. <br/>However, DASPs have to comply with disclosure and governance requirements under the AFS license if they are offering financial products "],
      "riskManagement": ["Partial","There are currently no risk management requirements for DASPs in Australia. <br/>However, DASPs have to comply with reserve and equity requirements under the AFS license if they are offering financial products "],
      "taxation":["Yes","The Australian Tax Office provides detailed guidance on when earnings from exchanging, trading, selling and issuing digital assets will constitute a taxable event. It also specifies when different kinds of tax may become applicable.  The capital gains tax rate for residents in Australia are: <br/>0 - 18,200: 0% <br/>10,201-45,000: 19%<br/> 45,001 - 120,000: 32.5% <br/> 120,001 - 180,000: 37% <br/> 180,001+: 45% <br/> Capital gains have to be reported as part of the Income Tax Return. There is a reduced tax on the disposal of long-term digital asset holdings <br/> GST may be also be applicable in some situations, particularly where the supply of mining services is involved"],
      "capitalControls":["No","Australia does not have a capital controls regime"],
      "amlCft":["Yes","New laws for 'digital currency exchange' (DCE) providers operating in Australia have been implemented by AUSTRAC, Australia’s financial intelligence agency and anti-money laundering and counter-terrorism financing (AML/CTF) regulator.<br/>DCEs with a business operation located in Australia must register with AUSTRAC and meet the Government’s AML/CTF compliance and reporting obligations.<br/>The Anti-Money Laundering and Counter-Terrorism Financing Act 2006 requires regulated entities to collect information to establish a customer’s identity, monitor transactional activity, and report to AUSTRAC transactions or activity that is suspicious or involves large amounts of cash over $10,000."],
      "grievanceRedressal":["Partial - General Legislation", "Investors in digital assets may have some recourse against deceptive or misleading conduct, but no specific dispute resolution or grievance redressal mechanism is prescribed by Australian Consumer Law <br/>ASIC has, however, indicated in its 2022-2026 Action Plan that the development of a regulatory framework for digital assets focus on consumer protection is a priority "],
      "dataProtection":["Partial - General Legislation","There are currently no specific data protection or information security practices that specifically apply to crypto-asset service providers in Australia, even though the country has a data protection regime in place  (Privacy Act, 1988"],
      "advertisingRegulations":["Yes","Misleading or deceptive conduct by entities issuing all kinds of digital assets, including ones that are not classified as financial products."],
      "consumerAwareness":["Under Consultation","The Australian Treasury's Consultation Paper on licensing for 'crypto asset secondary service providers' lists consumer awareness and education as one of the areas that requires regulatory intervention"],
      "investorProtection":["Partial","Info Sheet 225 states that digital assets that are financial products may be covered by insurance of compensation arrangements. However, the applicability of insurance schemes to digital assets that are not financial products remains unclear"],
      "restrictions":["Yes","Digital asset exchanges in Australia do not offer privacy coin like Monero and zCash. It is not clear if this due to explicit instructions or guidance from the Government"],
      "lat": "-25.2744",
      "lang": "133.7751"
    },
    {
      "countryName": "Brazil",
      "legalStatus": ["Legal","The Parliament has recently passed a law that specifically defines digital assets and creates a comprehensive legal framework."],
      "classification":["Yes","Digital Assets are defined as digital representations of value that can be traded or transferred by electronic means and used for making payments or for investment purposes. The following are not included in the definition: <br/>National Currency and Foreign Currency<br/>Electronic Money <br/>Instruments that provide holders with access to specified goods or services such as points and loyalty programmes <br/>Securities and financial assets that are regulated by other entities"],
      "licensing": ["Yes","All DASPs must obtain authorisation from a regulatory body to be established under House Law No 4401/2021 (this could be a new agency or an existing regulatory body). The following is included within the definition of providing services: <br/>a) Exchange between digital asset and fiat currency <br/>b) Exchange between different digital assets <br/>c) Custody or administration of digital assets <br/>d) Transfer of virtual assets <br/>e) Participation in financial services and provision of services related to an issuer’s offer or sale of virtual assets"],
      "corporateGovernance": ["Yes","The Act prescribes observance of the principles of good governance as an obligation for DASPs but does not define these principles"],
      "riskManagement": ["No","No capital reserve requirement or risk management practices are prescribed currently. Previous versions of House Law No. 4401/2021 required DASPs to separate assets, but this provision was omitted in the most recent draft"],
      "taxation":["Yes","The Brazilian Internal Revenue Service has clarified, through rulings and Q&As, that gains from digital assets are subject to capital gains tax, which ranges from 15% to 22.5%  <br/>CGT only applies where the total value of digital asset gains is more than 35,000 real. CGT is applicable even if there is no conversion into fiat currency"],
      "capitalControls":["No","While Brazil does have a capital control regime where transactions involving cross border transfers must be conducted through an authorised intermediary, these requirements have not been extended to virtual assets."],
      "amlCft":["Proposed","The new law includes DASPs in the list of institutions required to report data to the Council of Financial Activities Control <br/>Even before the law came into force, DASPs in Brazil were complying with the self-regulatory code put out by ABCrypto, an association of exchanges"],
      "grievanceRedressal":["Yes", "The protection and defense of consumers and users is a key obligation for DASPs as per House Law No 4401/2021 <br/>Sources suggest that the law also extends Brazil's Consumer Defense Code to DASPs, but this is not clear from a translated version of the text"],
      "dataProtection":["Partial - General Legislation","CASPs will likely be data controllers under the Brazilian General dataProtection Law. However, there are no specific requirements for such entitiesDASPs will likely be data controllers under the Brazilian General Data Protection Law. However, there are no specific requirements for such entities"],
      "advertisingRegulations":["No","Regulation on digital asset related ads does not exist currently"],
      "consumerAwareness":["No","While House Law No. 4401/2021 mentions consumer protection as a priority area, it does not contain specific measures to increase consumer awareness around digital assets"],
      "investorProtection":["No","House Law No. 4401/2021 does not specifically address the insurance of digital assets. Hence, the status of such assets for insurance purposes remains unclear at the moment"],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "-14.2350",
      "lang": "-51.9253"
    },
    {
      "countryName": "Canada",
      "legalStatus": ["Legal","The use of digital assets for investments, payment, trading and sale is legal in Canada"],
      "classification":["Yes","Canadian Securities Administrators have provided detailed guidance on when digital assets can be classified as securities, derivatives or crypto-contracts. <br/>The Canadian Revenue Agency (CRA) generally treats cryptocurrency like a commodity for purposes of the Income Tax Act."],
      "licensing": ["Yes","Provision of trading services in relation to securities, derivatives or crypto-contracts requires a license and registration with the relevant provincial securities authority. Several exchanges have obtained registration as Restricted Dealers' with the CSA<br/>Exchanges that provide spot purchases and immediate delivery of digital assets that are not securities do not need a license."],
      "corporateGovernance": ["Partial","Trading platforms and exchanges that offer digital assets that qualify securities, derivatives or crypto-contracts are required to fulfil minimum governance requirements as part of the registration process with the provincial securities regulator <br/>Similar requirements are not imposed on trading platforms or exchanges providing immediate spot delivery of digital assets"],
      "riskManagement": ["Partial","Trading platforms and exchanges that offer digital assets that qualify as securities, derivatives or crypto-contracts are required to make disclosures and adopt risk management practices as part of the registration process with the provincial securities regulator <br/>Similar requirements are not imposed on trading platforms or exchanges providing immediate spot delivery of digital assets"],
      "taxation":["Yes","The Canadian Revenue Agency (CRA) generally treats digital assets like a commodity for purposes of the Income Tax Act. Any income from transactions involving digital assets is generally treated as business income or as a capital gain, depending on the circumstances. Similarly, if earnings qualify as business income or as a capital gain then any losses are treated as business losses or capital losses.<br/>Canada uses personal income tax rates for capital gains as well. In Canada, taxation is done at both the federal and the provincial level. The federal tax rates of 2022 were: <br/>15% for the first $50,197 of taxable income<br/>20.5% for $50,197 - $100,392<br/>26% for $100,392 - $155,625<br/>29% for $155,625 - $221,708<br/>33% for $221,708+<br/>The various provinces of Canada have their own tax brackets."],
      "capitalControls":["No","Canada does not have a capital controls regime "],
      "amlCft":["Yes","FINTRAC is the main agency overlooking AML operations in Canada under Proceeds of Crime (Money Laundering) and Terrorist Financing Act (PCMLTFA). <br/>DASPs are considered as money services business (MSB), hence they are covered under the act."],
      "grievanceRedressal":["Partial - General Legislation", "The Financial Consumer Agency of Canada requires all regulated entities offering digital assets to abide by the Financial Consumer Protection Framework <br/>It is unclear if similar protections apply to offering by non-regulated entities i.e. trading platforms or exchanges providing immediate delivery of digital assets as opposed to those offering derivates, securities or crypto-contracts "],
      "dataProtection":["Partial - General Legislation","All companies handling user data, including DASPs, must comply with Personal Information Protection and Electronic Documents Act <br/>However, there are no specific privacy or data protection obligations for DASPs "],
      "advertisingRegulations":["Yes","A number of provisions in securities legislation and  Investment Industry Regulatory Organization of Canada rules apply to prohibit false or misleading statements in advertising or marketing materials used by DASPs"],
      "consumerAwareness":["Yes","Provincial Securities Commissions, such as in Ontaria, regularly undertake surveys to understand consumer knowledge and awareness of digital assets."],
      "investorProtection":["No","Digital assets are not eligible for insurance provided by the Canada Deposit Insurance Corporation"],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "56.1304",
      "lang": "-106.3468"
    },

    {
      "countryName": "China",
      "legalStatus": ["General Ban","Issuing, minting, trading and exchanging digital assets is outlawed in China. It is also illegal to offer services, such as account opening and fiat conversion, related to digital assets to Chinese residents<br/>However, the holding of a digital asset itself is not illegal. The private exchange of digital assets may also not be illegal.  <br/>Furthermore, providing blockchain-based information services is legal as long as they are not used to offer speculative trading on digital assets."],
      "classification":["No","No legal instrument specifically classifies digital assets as securities, commodities or creates a sui-generis class for their regulation.  "],
      "licensing": ["No","The provision of digital asset exchange, issuance and storage services by enterprises is illegal. Provision of such services by domestic companies or international companies could result in imprisonment and fines for company officials based in China. <br/>Blockchain information service providers (BISPs) must file details of their offerings and services with the Cyberspace Administration of China"],
      "corporateGovernance": ["No","The provision of digital asset exchange, issuance, and storage services by enterprises is illegal."],
      "riskManagement": ["No","The provision of digital asset exchange, issuance and storage services by enterprises is illegal. "],
      "taxation":["No","Even though provision of digital asset related services is illegal, overseas DASPs can be retroactively taxed on the services provided by them to Chinese citizens <br/>Reports also suggest that Chinese tax authorities have started implementing a 20% tax on profits from digital asset investments and from mining"],
      "capitalControls":["No","As cross-border exchanges of digital assets are illegal in China, no digital asset specific capital controls have been implemented.<br/>However, before trading/exchanging/issuing digital assets was illegal, Chinese authorities perceived it to be a key mechanism to evade capital controls. "],
      "amlCft":["No","The cross-border exchange of digital assets is illegal; hence, no AML/CFT are stipulated for DASPs.  However, financial institutions must comply with the nation's  Anti-Money Laundering Law. <br/>Before providing digital asset-related services was made illegal, internet companies providing such services were also required to comply with AML/CFT regulations. <br/>BISPs are required to collect real identification information, including organisations registration numbers, phone numbers etc."],
      "grievanceRedressal":["No", "There are no specific grievance redressal mechanisms related to digital assets as providing services related to them is illegal."],
      "dataProtection":["No","No specific requirements for DASPs. <br/>BISPs are required to implement security management solutions as prescribed by relevant Cyber Security legislation"],
      "advertisingRegulations":["Yes","Advertisements related to digital assets are prohibited with frequent monitoring of key words"],
      "consumerAwareness":["No","Given the general ban on providing services related to digital assets, there is no regulation aimed at improving consumer awareness of the risks "],
      "investorProtection":["No","There is no deposit insurance for digital assets in China  "],
      "restrictions":["Yes","Chinese companies are prohibited from offering services related to digital assets, including trading, exchanging and mining <br/>ICOs were also banned in China in 2017"],
      "lat": "35.8617",
      "lang": "104.1954"
    },
    {
      "countryName": "France",
      "legalStatus": ["Legal","The PACTE ((Action Plan for Business Growth and Transformation) Act is a legal framework for digital assets passed in 2019.<br/>France's digital asset regulations were further amended in 2021 via an ordinance that makes registration mandatory for 'crypto to crypto' services and expands KYC requirements  "],
      "classification":["Yes","The PACTE divides digital assets into: <br/>a. Utility Tokens <br/>b. Cryptocurrencies <br/>Stablecoins, NFTs and security tokens are not covered under this definition"],
      "licensing": ["Yes","French regulation of digital assets relies on two modes of authorization: <br/><b>Optional visa for Initial Coin Offerings</b>The French Financial Market Authority (AMF) introduced an optional visa regime for public offerings of utility tokens that are not financial instruments. This optional visa allows initial coin offerings (ICOs) to market directly to French citizens, whereas unregistered ICOs are subject to marketing restrictions. <br/><b>Mandatory Registration for certain DASPs</b><br/>Registration with the AMF is mandatory for:  <br/>- the purchase and sale of digital assets in legal tender or against other digital assets<br/>- operation of a trading platform and the custody of digital assets for third parties <br/><b>Optional Registration for other DASPs: </b><br/>Providers of other services such as portfolio management and investment advice currently do not need to register with MAF. Entities providing such services can also choose to obtain an optional license, which provides more avenues to reach consumers. <br/>A proposal to extend registration requirements to all digital asset service providers, even those not providing conversion to fiat currency, is before French Parliament. "],
      "corporateGovernance": ["Yes","DASPs seeking an optional license from the AMF must fulfil requirements related to commercial transaprency and prevention of conflicts of interests as per the PACTE "],
      "riskManagement": ["Yes","DASPs seeking an optional license must fulfil minimum equity and insurance requirements that are similar to those applicable to traditional financial players"],
      "taxation":["Yes","Capital gains on digital assets that are realised as a part of individuals' private asset management are taxable at a flat rate of 30%. <br/>If trade in digital assets happens on a regular basis by professional investors, gains may be subject to the progressive income tax rate in the category of non-industrial and commercial profits.  <br/>ICOs are subject to VAT only when the issued tokens are used by their holders. "],
      "capitalControls":["No","France does not have capital controls"],
      "amlCft":["Yes","Ordinance 2020-1544 expands the AML/CFT obligations applicable to DASPs and requires them to record data on all transactions, even below the FATF's $1000 threshold. <br/>Notably, details on transfers that do not involve digital assets must also be recorded."],
      "grievanceRedressal":["Yes", "The ACPR and the AMF are cooperating through a joint working group to detect instances of fraud and inform the public and professionals. The AMF also updates its blacklist of unauthorised actors. <br/>The AMF also exercises its authority to take legal action and block access to fraudulent sites. "],
      "dataProtection":["Yes","The French Data Protection Law is applicable to any kind of data processing that is undertaken by an establishment of a controller or processor in French territory. This can also apply to DASPs.<br/>The AMF has released cybersecurity system requirements for DASPs."],
      "advertisingRegulations":["Yes","Digital Asset Service Providers without optional licenses may not make direct solicitations or any direct or indirect advertisements. They also require AMF authorisation to recieve any sponsorship whose purpose/effect is to advertise directly/indirectly, a digital assets service."],
      "consumerAwareness":["Partial","The PACTE law does not include any clear references to increasing consumer awareness. However, regulatory authorities routinely issue advisories and warnings to consumers abut the risks of digital assets "],
      "investorProtection":["Yes","DASPs seeking a license under PACTE will be subject to 'core rules' applicable to all services, including subscription to a professional liability insurance "],
      "restrictions":["Yes","Only ICOs that have obtained approval from the AMF can market/promote themselves to French citizens.<br/>France has also banned privacy coins. "],
      "lat": "46.2276",
      "lang": "2.2137"
    },
    {
      "countryName": "Germany",
      "legalStatus": ["Legal","Digital assets are legal in Germany and can be used for a variety of financial purposes, including investments, transfers and payments "],
      "classification":["Yes","Digital Assets are recognised as financial assets and are classified based on their structure and functionality. <br/>The categories of classification include securities, payment systems and investments. Depending on the classification, a range of laws including Securities Law, Banking Law and Payments law may be applicable to crypto-assets. <br/>A recent amendment to the German Banking Act added a catch-all definition of 'crypto-asssets' meaning that such assets are regulated regardless of their classification."],
      "licensing": ["Yes","Providers of digital asset must generally obtain a license from the Federal Financial Supervisory Authority (BaFIN).<br/>Licensing requirements also apply to providers of digital asset custody services and security registers.<br/>Depending on how the digital assets are classified, licensing requirements under securities and payments law may be also be applicable"],
      "corporateGovernance": ["Yes","As per the licensing regime, digital asset custody providers and proprietary trading firms must appoint qualified and independent directors."],
      "riskManagement": ["Yes","The applicable risk management framework depends on how the digital asset in question is classified. In general, Circular 09/2017 on Minimum Risk Management Requirements is applicable to banks, investment services, and digital asset custody businesses. Among other things, the requirements prescribe internal capital adequacy norms for registered institutions. "],
      "taxation":["Yes","VAT – generally not applicable on digital asset transactions in Germany. Fees for providing wallet or exchange services may trigger VAT. <br/>Income Tax – the Ministry of Finance considers digital assets as immaterial assets that are subject to personal income tax. The applicable tax rate depends on the holder’s income slab and can range from 5.5% to 45%. <br/>Long-term holdings of digital assets (i.e. > than 1 year) are exempt from personal income tax provided they are not used to generate income via lending or staking. "],
      "capitalControls":["No","Germany does not have capital controls"],
      "amlCft":["Yes","DASPs must capture and provide relevant AML information to BaFIN as Germany has incorporated EU AML Directive 5 into local legislation. AMLD5 is a recent iteration of the EU Anti-Money Laundering provisions that bring digital assets within the scope of reporting and KYC requirements. <br/>They must also implement robust KYC mechanisms "],
      "grievanceRedressal":["Partial - General Legislation", "There are no specific grievance redressal mechanisms that DASPs need to put in place. <br/>However, internet platforms that offer trading or exchange service may be required to adhere to provisions in EU Consumer Protection Directives that have been accepted in Germany.       "],
      "dataProtection":["Yes","Licenses for digital asset custody service providers and other financial institutions require them to employ trained information security personnel, have in place a robust IT security architecture and conduct risk assessments. "],
      "advertisingRegulations":["Yes","Individuals or enterprises commercially involved with digital assets must avoid misleading or factually incorrect advertising "],
      "consumerAwareness":["Partial","Though not specifically mentioned as an objective in BaFin or other regulation, German regulatory authorities regularly issue advisories and warnings to consumers about the risks of digital assets "],
      "investorProtection":["No","BaFin has also clarified that traditional deposit insurance and investor compensation schemes do not apply to digital assets. Any recovery of assets for consumers in case a DASP ceases to operate will depend on insolvency laws and agreements between the provider and customers. "],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "51.1657",
      "lang": "10.4515"
    },
    {
      "countryName": "India",
      "legalStatus": ["Legal","In 2018 RBI prohibited dealing in digital assets via an RBI notification (RBI/2017-18/154). The Indian Supreme Court in the matter of Writ Petition (Civil) No.528 of 2018 (Internet and Mobile Association of India v. Reserve Bank of India) has set aside the said prohibition in 2020. Presently there is no ban on dealing in digital assets. <br/>The Finance Minister and Secretary for Economic Affairs have stated that regulations for digital assets would be introduced in the forthcoming year - providing further evidence of their legality in the country."],
      "classification":["No","While digital assets are legal in India, a specific framework is yet to be adopted. A definition for 'virtual digital assets' (VDAs) has been included in the Income Tax Act. They are defined as: <br/>(a) any information or code or number or token (not being Indian currency or foreign currency), generated through cryptographic means or otherwise, by whatever name called, providing a digital representation of value exchanged with or without consideration, with the promise or representation of having inherent value, or functions as a store of value or a unit of account including its use in any financial transaction or investment, but not limited to investment scheme; and can be transferred, stored or traded electronically;<br/>(b) a non-fungible token or any other token of similar nature, by whatever name called;<br/>(c) any other digital asset, as the Central Government may, by notification in the Official Gazette specify "],
      "licensing": ["No","There is no specific licensing regime for DASPs. The Companies Act requires all companies to declare their digital asset holdings"],
      "corporateGovernance": ["No","No specific corporate governance requirements are prescribed for DASPs"],
      "riskManagement": ["No","No specific risk management requirements are prescribed for DASPs  "],
      "taxation":["Yes","A new section 115BBH has been inserted in the Act to provide a tax of 30% on income from 'virtual digital assets'. A 1% TDS is also applicable on all digital asset transactions.  "],
      "capitalControls":["No","India has a managed capital account. The Reserve Bank regulates capital flows through the Foreign Exchange Management Act. Digital assets are yet to be brought under the Act's ambit. <br/>However, the enforcement agency for FEMA has investigated digital asset exchanges for their role in transferring funds across borders.    "],
      "amlCft":["No","The Government has included digital assets under the ambit of the Prevention of Money Laundering Act. The notification requires businesses carrying out the following activities will be considered reporting entities for AML/CFT purposes: <br/>(i) exchange between virtual digital assets and fiat currencies;<br/>(ii) exchange between one or more forms of virtual digital assets;<br/>(iii) transfer of virtual digital assets;<br/>(iv) safekeeping or administration of virtual digital assets or instruments enabling control over virtual digital assets; and<br/>(v)participation in and provision of financial services related to an issuer’s offer and sale of a virtual digital asset."],
      "grievanceRedressal":["Partial - General Legislation", "The Reserve Bank of India has stated that it has not given any licence/authorisation to any company to  deal with  digital assets  and users bear the risk of their digital asset investments <br/>However, the general Consumer Protection Act should apply to DASPs, especially in light of recent amendments that specifically brought the online provision of services within the Act's ambit "],
      "dataProtection":["No","There are no specific data protection and information security requirements for DASPs.  "],
      "advertisingRegulations":["Yes","The Advertising Standards Council of India (ASCI) has released the guidelines regarding digital endorsement/advertisement. All ads for digital asset products and digital asset exchanges, or featuring digital assets, must carry relevant disclaimers. "],
      "consumerAwareness":["Partial","Ministers and officials of the Central Bank have warned consumers against the perils of investing in digital assets. <br/>However, there is no regulatory push toward increasing consumer awareness "],
      "investorProtection":["No","The RBI has clarified that deposit insurance and credit guarantees do not apply to digital assets  "],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "20.5937",
      "lang": "78.9629"
    },
    {
      "countryName": "Indonesia",
      "legalStatus": ["Legal","The Ministry of Trade and Commodity Futures Trading Supervisory Agency (BAPPEBTI) recognises digital assets as commodities and allows their trading on a futures basis, subject to regulatory requirements"],
      "classification":["Yes","There is no specific classification of digital assets. <br/>However, only assets approved by BAPPEBTI can be traded. In approving assets, BAPPEBTI looks at:  <br/>- Digital Asset market capitalization value (coin market cap);  <br/>- Is transacted on the world's largest digital asset exchanges;  <br/>- have economic benefits related to taxation, digital economic growth, impact to the information technology industry and the competence of experts in the field of informatics (digital talent); and <br/>- undergone risk assessment, including the risk of money laundering and terrorism financing as well as the proliferation of weapons of mass destruction. "],
      "licensing": ["Yes","BAPPEBTI issues licenses for a number of entities involved in digital asset trade, including: <br/>Physical digital asset traders <br/>Futures Clearing House <br/>Futures Exchange <br/>Digital Asset Storage Manager <br/>The regulations prescribe different requirements for each entity, including minimum capital requirements, minimum equity holding and the number of certified workers.       "],
      "corporateGovernance": ["Yes","Regulation 5/2019 and 8/2021 specify that entities providing digital asset futures trading must comply with minimum organisation requirements, including an audit division, legal division, and accounting and finance divisions "],
      "riskManagement": ["Yes","Regulations require exchanges to maintain user funds in separate accounts. 95% of funds must also be stored offline and in cold storage "],
      "taxation":["Yes","Since digital assets are treated as commodities, VAT and capital gains at the rate of 0.1%."],
      "capitalControls":["No","Indonesia implements some restrictions on the flow of capital across borders. However, these have not been extended to cryptoassetsIndonesia implements some restrictions on the flow of capital across borders. However, these do not appear to have been extended to digital assets"],
      "amlCft":["Yes","Digital assets are only approved for trading after the BAPPEBTI studies the AML/CFT risk posed by each. <br/>Regulations require brokers, exchanges and clearing houses to adopt mechanisms to check AML/CFT and implement detailed KYC procedures <br/>Exchanges also must report any suspicious transactions to the BAPPEBTI "],
      "grievanceRedressal":["Yes", "BAPPEBTI regulations prescribe a detailed grievance redressal mechanism to deal with complaints by users of DASPs<br/>It also provides avenues for appeal in case a complaint is not resolved at the level of the DASP      "],
      "dataProtection":["Yes","The regulations require exchanges, clearing houses, brokers and storage managers to comply with various information security requirements, including:<br/>- employment of individuals with CISSP cetification <br/>-- location of servers within Indonesia <br/>- Regular audits by third-parties <br/>- ISO 27001 regulations "],
      "advertisingRegulations":["No","There do not appear any specific guidelines for regulating digital asset related ads and marketing "],
      "consumerAwareness":["Yes","BABPPEBTI regulations specifically include reducing information asymmetries between issuers and investors as a guiding principle for regulation"],
      "investorProtection":["No","Regulations governing digital assets do not provide for insurance of investor protection in case of a loss "],
      "restrictions":["No","Digital assets cannot be used as a means for payment as per the Currency Law of 2011.<br/>Financial service institutions are also barred from using, marketing and facilitating digital asset trading."],
      "lat": "-0.7893",
      "lang": "113.9213"
    },
    {
      "countryName": "Italy",
      "legalStatus": ["Legal","While crypto-assets are not specifically regulated, they have not been prohibited by Italian legislation. Rules for AML/CFT compliance have been enacted. "],
      "classification":["No","There is no legal classification for crypto-assets currently. However, crypto-assets may be regarded as financial instruments or products if they fulfil certain requirements under Italian securities and banking law.  <br/>Moreover, Italian courts have classified crypto-assets as financial products and 'fungible goods' in different cases. Hence, there is little clarity over the current classification of crypto-assets "],
      "licensing": ["Yes","All crypto-asset service providers and wallet providers have to notify the Italitan OAM and register their operations."],
      "corporateGovernance": ["No","There are no specific corporate governance obligations that crypto-asset service providers and wallet providers need to fulfil "],
      "riskManagement": ["No","No minimum capital or reserve requirements are prescribed for crypto-asset service providers at the moment. "],
      "taxation":["Yes","Capital gains tax and corporate tax are applicable on profits from crypto trading. Capital gains only applies if n individual's portfolio value is above 51,000 euros for seven consecutive days in a year. <br/>VAT is not applicable on crypto-trading in Italy. "],
      "capitalControls":["No","Italy does not have capital controls"],
      "amlCft":["Yes","Italy has implemented EU AMLD 5, as a result of which crypto exchanges, wallet providers and other service providers must comply with AML/CFT requirements. These include customer due diligence, record retention and transaction reporting"],
      "grievanceRedressal":["Partial - General Legislation", "The EU Omnibus Directive, which reforms consumer law and provides conumers with new avenues of recourse has been implemented in Italy. However, there are no specific obligations for crypto-exchanges and wallet providers"],
      "dataProtection":["Partial - General Legislation","The GDPR is the primary privacy legislation in Italy and may apply to crypto exchanges and wallet service providers who can be considered data controllers. However, the provisions of the Regulation have not been specifically extended to these entitites"],
      "advertisingRegulations":["No","There are no rules or guidelines regarding the advertisement and marketing of crypto products and services"],
      "consumerAwareness":["",""],
      "investorProtection":["",""],
      "restrictions":["",""],
      "lat": "41.8719",
      "lang": "12.5674"
    },
    {
      "countryName": "Japan",
      "legalStatus": ["Legal","Cryptocurrency and utility tokens such as BTC & ETH are regulated as digital assets under the Payment Services Act (PSA).<br/>However, tokens that meet the requirements of security are regulated under the Financial Instruments and Exchange Act (FIEA). Issuance of stablecoins is regulated under the Banking Act and the Trust Business Act. "],
      "classification":["Yes","The PSA defines digital assets as: <br/>1. Property value that:<br/>– can be used by unspecified persons for payment of equivalent value for purchased goods, rental fees, or services, <br/>– can be purchased by or sold to unspecified persons<br/>– is transferable via an electronic data processing system (limited to property values that are stored electronically on electronics, excluding currency and currency denominated assets); or<br/>2. Property value that can be mutually exchangeable for one above with unspecified persons and is transferable via an electronic data processing system. <br/>There is no specific legislative classification of digital assets in Japan. However, stablecoins are regulated separately. <br/>Here too, algorithmic stablecoins are treated differently from other stablecoins and are not regulated under the Banking Act or Trust Business Act. "],
      "licensing": ["Yes","Yes, all 'crypto-asset exchange service providers' (CAESPs) must register with the Financial Services Authority and adhere to guidelines imposed by self-regulatory organisations. <br/>CAESPs and intermediaries include: <br/>1. Platforms for the sale and purchase of digital assets<br/>2. Intermediary brokerage or agency services <br/>3. Management of customer assets <br/>4. Management of crypto-assets on behalf of another <br/>CAESPs can only offer tokens that self-regulatory organisations (SROs) have approved. There are currently two self-regulatory organisations for digital assets in Japan - the Japan Virtual Currency Exchange Association and Japan Security Token Offering Association. <br/>Issuers of digital assets, besides stablecoins, are not considered intermediaries. <br/>CAESPs providing digital asset-derivates must obtain a separate license under the FIEA. "],
      "corporateGovernance": ["No","The amended PSA does not prescribe specific corporate governance norms for CAESPs.<br/>However, the activities of CAESPs are subject to self-regulatory rules and guidelines developed by the Japan Virtual Currency Exchange Association and Japan Security Token Offering Association. <br/>CAESPs can be ordered to improve the operation of their business by the FSA or by SROs "],
      "riskManagement": ["Yes","The 2017 Amendment to the PSA requires CAESPs to keep the business and customer wallets separate and keep 95% of assets in cold storage (not connected to the internet).  <br/>Other risk management practices include operational risk and cyber security management, Know-Your-Customer, internal audits, and minimum capital requirements."],
      "taxation":["Yes","The gains generated by the sale or use of digital assets are to be treated as miscellaneous income and are taxed at rates of 15% to 55% (for individuals) and 30% (for corporations). However, such gains cannot be offset against losses incurred elsewhere. Taxes apply on realised and unrealised gains from digital assets. <br/>Additionally, digital assets held in the estate of a deceased person are subject to inheritance tax."],
      "capitalControls":["No","Japan lifted capital controls in the 1980s"],
      "amlCft":["Yes","CAESPs are subject to AML/CFT requirements under the Prevention of the Transfer of Criminal Proceeds Act and the Foreign Exchange and Foreign Trade Act respectively. <br/>These requirements include:<br/>1. KYC checks upon the opening of an account. In addition, a declaration of beneficial ownership is required in the case of corporate customers;<br/>2. Reporting suspicious transactions to the Japan Financial Intelligence Centre and the Japan Financial Intelligence Unit;<br/>3. Record production and retention requirements; and<br.>4. Politically exposed person monitoring      "],
      "grievanceRedressal":["Yes", "PSA requires exchanges to establish internal control systems for responding to user complaints and take measures to resolve disputes through alternative dispute resolution procedures."],
      "dataProtection":["Yes","The PSA requires exchanges to take necessary measures to ensure the security of important information such as personal information and information on private keys to digital assets; establish a risk management system to prevent system failures and cyber incidents; and establish contingency plans to deal with exigencies and provide training for the same.      "],
      "advertisingRegulations":["Yes","DASPs are subject to regulations regarding advertisement and solicitation under PSA. False representations, exaggerated advertising and advertisements and solicitation that encourage speculation are prohibited. <br/>Where the sales proceeds of the digital assets are to be used for services or applied to the operation of a business operated by the issuer, or where the price is linked to underlying assets, investor explanations are required to include a rational explanation of the basis for the sales price."],
      "consumerAwareness":["Yes","Digital asset exchanges are required to provide accurate information to users about their offerings, fees etc."],
      "investorProtection":["Partial","Stablecoins can only be issued by regulated financial entities and, hence, are protected by deposit insurance <br/>The same protection does not appear to extend to other digital assets "],
      "restrictions":["Yes","Restrictions are placed on the issuance of stablecoins. Only bank, fund transfer service providers and trust companies are allowed to issue stablecoins to Japanese citizens. <br/>Japan has banned the use of all digital assets that provide a sufficient degree of anonymity, inclusing Monero, Dash and ZCash. "],
      "lat": "36.2048",
      "lang": "138.2529"
    },
    {
      "countryName": "Mexico",
      "legalStatus": ["Partial Ban","Mexico's FinTech law explicitly recognises digital assets as 'virtual assets,' which differ from currencies.<br/>While the text of the law creates an enabling framework for the use of digital assets by financial institutions, subsequent notifications by the Central Bank have clarified that financial institutions can use digital assets only for 'internal transactions'.  "],
      "classification":["Yes","There are no specific regulations on data protection and information security applicable to DASPs. <br/>However, Mexico has a general data protection law, The Federal Law on the Protection of Personal Data held by Private Parties, that may apply to DASPs."],
      "licensing": ["No","Digital Assets are classified as virtual assets as per the FinTech Law. Virtual assets are defined as: <br/>'representation of value recorded electronically and used among the public as a means of payment for all kinds of legal acts and whose transfer can only be carried out by electronic means.'  <br/>They are not regarded as legal tender or currency       "],
      "corporateGovernance": ["No","There is no specific license for non-financial entities that provide digital asset-related services. <br/>However, companies providing a facility to convert digital assets into fiat must register themselves as Electronic Payment Fund Institutions and comply with provisions of the FinTech law. <br/>While financial institutions, specifically credit institutions, financial technology institutions, payment fund institutions, and collective financing institutions, were initially permitted to use digital assets for certain services, the Central Bank has stated that such assets should be kept away from the nation's financial system.  "],
      "riskManagement": ["No"," The FinTech law and related regulations do not prescribe any corporate governance norms for non-financial entities providing digital asset-related services "],
      "taxation":["No","Tax laws in Mexico have not been amended to include digital assets specifically. <br/>However, since digital assets are classified as virtual assets under FinTech law, they may be considered intangible property. </br>As such, individuals and companies are required to pay capital gains on digital assets earnings in accordance with Mexico's Income Tax Law.  <br/>The rate of tax for individuals increases progressively to 35% whereas corporations have a flat 30% tax rate. <br/>Value Added Tax may also apply to the provision of digital asset-related services by Mexican entities. However, there is no clear communication or precedent in this regard. The general rate of VAT is 16% in Mexico.       "],
      "capitalControls":["No","Mexico has no capital controls "],
      "amlCft":["Yes","Mexico amended its AML/CFT regulations as part of its modernisation of banking and financial laws. <br/>Non-financial entities that provide digital asset-related services have to register with the Financial Intelligence Unit - Mexico's illicit financing regulator. They must also comply with KYC requirements and report all transactions above a monetary threshold to the FIU. <br/>The nation complies with the requirements of Rule 16 of FATF (Travel Rule)      "],
      "grievanceRedressal":["Partial - General Legislation", "DASPs are subject to the Federal Consumer Protection Law. However, there are no specific requirements for such institutions at the moment. "],
      "dataProtection":["Partial - General Legislation","There are no specific regulations on data protection and information security applicable to DASPs. <br/>However, Mexico has a general data protection law, The Federal Law on the Protection of Personal Data held by Private Parties, that may apply to DASPs. "],
      "advertisingRegulations":["No","There do not appear any specific guidelines for regulating digital asset-related ads and marketing at the moment  "],
      "consumerAwareness":["Yes","Rules issued by Mexico’s consumer watchdog require fintechs to provide consumers with detailed information on fees, interest rates and risks associated with services offered by the fintech."],
      "investorProtection":["No","Digital Assets do not appear to be covered by insurance that applies to other financial products "],
      "restrictions":["Yes","Financial institutions are prohibited from using virtual assets for settlement or offering services related to virtual assets. Only non-financial institutions, i.e. ones not regulated by the Central Bank, can provide digital asset-related services to users."],
      "lat": "23.6260",
      "lang": "-102.5375"
    },
    {
      "countryName": "Russia",
      "legalStatus": ["Legal","Trading, mining, issuing and investing in digital assets is legal in Russia.<br/>The Ministry of Finance presented a framework regulation for digital assets to the Russian Government in February 2022. The draft Federal Law seeks to establish a regulatory framework covering:<br/>- corporate governance <br/>- reporting and disclsoures <br/>- information storage <br/>- internal control and audit  <br/>- risk management systems <br/>- licensing requirements <br/>- asset segregation <br.>However, the text of the BIll or detailed reports on it are not currently available. Hence, the proposed draft Bill has not been considered in assessing digital asset regulation in Russia. "],
      "classification":["Yes","Federal Law 259-FZ uses two different terms: digital financial assets and digital currencies. <br/>Digital financial assets (DFAs) are digital rights certifying one of the following: <br/>i. monetary claims <br/>ii. power to exercise rights in relation to registrable securities <br/>iii. right to shares in a private joint stock company <br/>iv. right to claim a transfer of registrable securities where the issuance, recording and circulation are only possible via making records in the information system on the basis of DLT <br/>As such, DFAs can be thought of as security or credit tokens issued using DLTs. Most digital assets would not meet the requirements of a DFA, and would instead be classified as a Digital Currency, which is: a set of electronic data contained in an information system which is and or may be offered as a payment instrument, not backed by the Russian or any foreign currency and in respect of which there is no person responsible to each holder of that electronic data' <br/>While the issuance and circulation of DFAs are regulated by the Federal Law, digital currencies are left largely unregulated."],
      "licensing": ["Yes","Federal Law lays down licensing procedures and requirements for information service providers and DFA exchanges.<br/>Only Russia legal entities are permitted to be information system operators and exchange providers.    <br/>No licensing requirements are prescribed for digital currencies.       "],
      "corporateGovernance": ["Yes","Russia laws prescribe minimum qualifications and requirements for executives of information system operators and DFA exchange providers. "],
      "riskManagement": ["No","There do not appear to be  specific capital reserve or risk management requirements for DFAs or digital currencies. "],
      "taxation":["Proposed","The lower house of Russian Parliament approved bill no. 1065710-7 that classifies digital assets as property and requires taxpayers to report digital assets holdings. <br/>Another Bill, no. 106872-8, has also been approved by the Lower House. This Bill exempts DFA information system operators and exchange service providers from the requirements of VAT. <br/>Personal income tax will be levied on the financial result of transactions with digital financial assets. "],
      "capitalControls":["No","While Russia has imposed stringent capital control measures to prevent capital flight due to war sanctions, these have not been explicitly extended to DFAs. Reports suggest the use of stablecoins to evade capital controls in Russia."],
      "amlCft":["Yes","Licensed DFA information system operators and exchange service providers must implement AML/CFT measures, including client identification, data collection, and reporting of transactions. <br/>It remains unclear whether AML/CFT obligations extend to providers of digital currencies. "],
      "grievanceRedressal":["Partial - General Legislation", "Russia has a law on consumer rights protection that creates mechanisms to redress consumer disputes, including consumer associations. However, there are no specific rules for DASPs.  "],
      "dataProtection":["Yes","Information systems operators must ensure the smooth and continuous operation of the system and the accuracy of records contained in the system. "],
      "advertisingRegulations":["Yes","No advertisement is permitted until a resolution on the DFA issue has been published. Any advertisement materials may not promise any profit on the DFAs or contain any projections in relation to the growth of their market value <br/>Advertisements related to digital currencies are completely prohibited."],
      "consumerAwareness":["Partial","Generating consumer awareness and providing relevant information is not specifically mentioned in Russia Federal Law or other regulations. <br/>However, the Central Bank has issued advisories warnings citizens about digital assets from time to time. It has also proposed a complete ban on all digital assets. "],
      "investorProtection":["No","There do not appear to be any regulations or guidance regarding investor protection for DFA and digital currency holders "],
      "restrictions":["Yes","Federal Law 259-FZ prohibited the use of digital currencies as a means of payment. In 2021, another law was adopted which extend this prohibition to DFAs as well.  "],
      "lat": "61.5240",
      "lang": "105.3188"
    },
    {
      "countryName": "Saudia Arabia",
      "legalStatus": ["Legal","Holding, trading, and investing in digital assets is legal in Saudi Arabia. However, the Standing Committee on Dealing in Unauthorised Securities Activities in the Foreign Exchange Market has banned financial institutions from dealing in or with digital assets.       "],
      "classification":["No","Digital assets are not classified under any legislation or regulation. "],
      "licensing": ["No","Financial institutions are not allowed to provide any digital asset-related services. There is no licensing regime for DASPs."],
      "corporateGovernance": ["No","There are no specific corporate governance requirements applicable to of crypto-related services"],
      "riskManagement": ["No","There are no specific risk management requirements applicable to DASPs"],
      "taxation":["No","No tax is levied on the income of an individual if it is derived from employment in Saudi Arabia. <br/>VAT is charged @ 15%. However, it is unclear if such tax extends to DASPs "],
      "capitalControls":["No","Saudia Arabia imposes no foreign exchange restrictions"],
      "amlCft":["Yes","The provisions of Royal Decree M/21 on combating terrorism extend AML/CFT reporting and due diligence obligations to DASPs "],
      "grievanceRedressal":["No", "There are no specific rules or regulations on consumer protection for DASPs. A draft of a comprehensive Consumer Protection Law is currently being discussed."],
      "dataProtection":["Partial - General Legislation","DASPs are not subject to any data protection or information security regulations beyond the nation's Personal Data Protection Law "],
      "advertisingRegulations":["Yes","While there are no guidelines of rules governing marketing, a Government standing committee 'works with relevant parties to reduce marketing for investment and trading in virtual currency'"],
      "consumerAwareness":["Partial","The Standing Committee and Ministry of Finance have warned against the use of digital assets but there is no specific focus on generating consumer awareness about digital assets<br/>Government agencies have also reiterated the potential dangers of digital assets and discouraged investment in them. "],
      "investorProtection":["No","Digital assets are outside Saudi Arabia's  regulatory framework and, hence, it appears that there are no specific protections or insurance covers for digital asset holders and investors "],
      "restrictions":["Yes","The Standing Committee on Dealing in Unauthorised Securities Activities in the Foreign Exchange Market has banned financial institutions from processing transactions involving cryptocurrencies.      "],
      "lat": "24.774265",
      "lang": "46.738586"
    },
    {
      "countryName": "South Africa",
      "legalStatus": ["Legal","Digital assets are treated as financial products under the Financial Advisory and Intermediary Services Act. The South African Crypto Asset Regulatory Working Group (CARWG) has also issued a consultation paper on policy proposals for the regulation of digital assets. However, the recommendations made by the working group are yet to be implemented.         "],
      "classification":["Yes","Digital assets are classified as financial products. Resultantly, all DASPs are subject to the same regulatory regime as other financial institutions under the Financial Advisory and Intermediary Services Act. They are defined as: <br/>'Crypto assets are digital representations or tokens that are accessed, verified, transacted, and traded electronically by a community of users. Crypto assets are issued electronically by decentralised entities and have no legal tender status, and consequently are not considered as electronic money either.'<br/>The Declaration does not apply to NFTs and digital asset derivates.       "],
      "licensing": ["Yes","Any legal person who renders financial services related to digital assets as part of regular business must obtain a license from the Financial Services Conduct Authority (FSCA). This definition should include exchanges, storage providers and wallet service providers. <br/>Mining nodes and node operators are exempt from licensing requirements.  "],
      "corporateGovernance": ["Yes","Persons providing financial services related to digital assets (referred to as digital asset FSPs in the FSCA Declaration) must comply with the provisions of the FAIS Act and sub-regulations, which include fit and proper tests and the management of conflict of interest "],
      "riskManagement": ["Yes","All digital asset FSPs must establish internal risk management policies, including segregation of funds, audits and regular disclosures. "],
      "taxation":["Yes","Citizens must pay income tax on profits from digital assets as per standard tax rates"],
      "capitalControls":["Proposed","South Africa controls the flow of foreign exchange and assets cross border.<br/>A Government working group has recently recommended the inclusion of crypto-assets under the Exchange Control Regulations. The implementation of this recommendation would allow authorised dealers to send digital assets across borders provided they adhere to reporting requirements      "],
      "amlCft":["Yes","Entities providing services related to crypto-assets have been included as 'Accountable Institutions' under the Financial Intelligence Centre Act and must conduct KYC and due diligence on all customers and establish a Risk Management and Compliance Program "],
      "grievanceRedressal":["Yes", "Digital asset FSPs must create effective complaints management processes."],
      "dataProtection":["Partial - General Legislation","Digital asset FSPs are subject to South African legislation and regulations on privacy. However, there are no specific information security or privacy requirements applicable specifically to entities providing digital asset related services. "],
      "advertisingRegulations":["Yes","Digital asset FSPs must abstain from false or misleading activities in connection with their products or serivces."],
      "consumerAwareness":["Partial","There are no specific requirements for generating consumer awareness in the Declaration or in the policy document supporting it. However, the FSCA has issued warnings to consumers about the risks associated with digital assets. "],
      "investorProtection":["No","The FSCA's declaration states that fidelity insurance requirements applicable to other financial intermediaries will not apply to digital asset FSPs <br/>Para 5.5.4, Policy Document Supporting the Declaration "],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "-30.5595",
      "lang": "22.9375"
    },
    {
      "countryName": "South Korea",
      "legalStatus": ["Legal","Digital assets are not legal tender in South Korea but can be used for remittances, payments, and as an investment. <br/>The Financial Services Commission (FSC) published guidance in 2023 stating that digital assets that fit the characteristics laid out in the Capital Markets Act will be treated as securities.  <br/>A comprehensive regulation for digital assets, known as the Digital Assets Basic Act is expected to be finalised in 2023. "],
      "classification":["Yes","TThe Act on Reporting and Using Specialised Finance Transactions defines “virtual assets (VAs)” as digital tokens with economic value that can be digitally traded or transferred. It does not provide any other categories of such assets. <br/>The FSC guidance on security tokens defines them as digitized versions of Securities under the Capital Markets Act using Distributed Ledger Technology. The Capital Markets Act's definition of securities is based on the Howey test (developed in the US to determine whether an instrument is an investment contract). The parameters for determining whether an instrument is a security include: <br/>a) Investment of money <br/>b) in a common enterprise <br/>c) With the expectation of profit <br/>d) to be derived from the efforts of others<br/>Issuers of digital assets are required to self-assess whether their assets qualify as securities under the Capital Markets Act. If this is the case, they will be subject to regulatory requirements under the Capital Markets Act. "],
      "licensing": ["Yes","Under the Act on Reporting and Using Specialised Finance transactions, all DASPs are required to register with the Korea Financial Intelligence Unit (KoFIU). <br/>Entities performing the following functions are classified as 'virtual asset service providers': <br/>i) purchase and sales of virtual assets; <br/>(ii) exchanges between virtual assets; <br/>(iii) transfer of virtual assets; <br/>(iv) safekeeping and administration of virtual assets; <br/>(v) intermediation or brokerages of virtual asset transactions; exchange of virtual assets; and (vi) other activities specified by the enforcement decree.  <br/>To register with KoFIU, DASPs must- <br/>1. Register an authorised company bank account and provide customers with their own real-name accounts with the same bank.<br/>2. Acquire an Information Security Management Systems (ISMS) certification from the Korea Internet and Security Agency (KISA)"],
      "corporateGovernance": ["Yes","The Korean Blockchain Association has introduced a self-regulatory code that covers aspects including organisational transparency and insider trading.<br/>The Korean Blockchain Association and its self-regulatory code have not been specifically approved or endorsed by South Korean financial regulators. "],
      "riskManagement": ["Yes","The Act on Reporting and Using Specialised Finance Transfers require DASPs to separate consumer digital asset deposits as well as the management of consumer transaction records."],
      "taxation":["Yes","DASPs in South Korea are subject to a 24.2% corporation tax. <br/>The levy of income tax or capital gains is less clear. A proposal to tax digital asset gains exceeding 2.0 million Korean won was introduced in 2021. However, its implementation has been pushed back to 2025 in the face of public opposition."],
      "capitalControls":["No","While South Korea controls capital flows through the Foreign Exchange Transactions Act, there is no guidance on how digital assets fit within this framework. <br/>In practice, banks do not process cross-border transactions that would fall foul of FETA. "],
      "amlCft":["Yes","On 5 March 2020, South Korea revised the Act on the Reporting and Use of Specific Financial Transaction Information. The amendment extends the AML/CTF rules to DASPs. <br/>Under the amended Act, all DASPs must mandatorily establish AML/KYC procedures which include customer due diligence and suspicious transactions reporting. <br/>This also requires a technical solution, which permits exchanging customers’ personal data with transaction counterparties."],
      "grievanceRedressal":["Yes", "The self-regulation code adopted by the Korea Blockchain Association includes 'general measures to protect consumers'. <br/>The association also has a dedicated Industry Self Regulation Committee "],
      "dataProtection":["Yes","Crypto service providers must acquire an Information Security Management Systems (ISMS) certification from the Korea Internet and Security Agency (KISA)"],
      "advertisingRegulations":["No","No specific limitations or restrictions are placed on advertisements of digital assets and related services. "],
      "consumerAwareness":["Partial","The current regulatory regime does not specifically create initiatives to increase consumer awareness of digital assets <br/>However, regulatory authorities such as the Financial Services Commission, have issued advisories relating to the use of digital assets. "],
      "investorProtection":["No","There is no statement/guideline/regulation that indicate the inclusion of digital assets under the Korea Deposit Insurance Corporation's jurisdiction."],
      "restrictions":["Yes","Initial Coin Offerings and margin trading on digital assets in banned in South Korea. <br/>Anonymous trading is also banned on domestic digital asset exchanges. <br/>Public officials cannot hold or invest in digital asets "],
      "lat": "35.9078",
      "lang": "127.7669"
    },
    {
      "countryName": "Turkey",
      "legalStatus": ["Legal","Digital assets are legal. <br/>A comprehensive regulatory framework for digital assets has been proposed. However, the framework legislation has so far not been introduced in Parliament."],
      "licensing": ["No","No licensing mechanism is prescribed for DASPs. <br/>However, the issuance of tokens through ICOs may fall within the CMB's (Turkey's Markets Regulator) jurisdiction."],
      "corporateGovernance": ["No","There do not appear to be any corporate government rules applicable to DASPs. <br/>However, the proposed framework regulation for digital assets will reportedly establish operating requirements for digital assets. "],
      "riskManagement": ["No","There are no risk management rules prescribed for DASPs"],
      "taxation":["No","No tax has been explicitly extended to digital assets thus far. <br/>While tax liability may arise if digital assets are considered to be securities or other financial products, there is no official guidance in this regard<br/>The New Economy Program 2020 announced that tax regulation for the acquisition, purchase, sale, and transfer of digital assets would be introduced between 2021 and 2023 "],
      "capitalControls":["No","Turkey has reintroduced restrictions on foreign exchange and capital flows in the wake of its currency crisis. However, it is unclear if these limitations apply to cross-border transfers involving digital assets"],
      "amlCft":["Yes","DASPs are considered 'obliged parties' under Tukey's Regulation on Measures Regarding Prevention of Laundering Proceeds.<br/>Resultantly, they must conduct thorough KYC and customer due diligence, report suspicious transactions and provide information and documents when requested by the Financial Crimes Investigation Board (FCIB)"],
      "grievanceRedressal":["Partial - General Legislation", "Turkey has general consumer protection and e-commerce laws and regulations that may apply to DASPs. However, there is no official communication to this effect"],
      "dataProtection":["Partial - General Legislation","General laws and regulations enacted by Turkey to protect user personal data, including the Law on The Protection of Personal Data, may apply to DASPs "],
      "advertisingRegulations":["No","There are no advertising guidelines for crypto products or service providers "],
      "consumerAwareness":["No","Current regulations do not address generating awareness or providing users with adequate information regarding the digital asset being offered "],
      "investorProtection":["No","Digital Assets do not appear to be covered by insurance that applies to other financial products "],
      "restrictions":["Yes","Digital assets cannot be used for payments, directly or indirectly.<br/>Services for the direct and indirect use of digital assets can also not be provided. <br/>Payment and electronic money institutions cannot 'mediate' platforms that offer trading, storage, transfer, or issuance services related to digital assets "],
      "lat": "38.9637",
      "lang": "35.2433"
    },
    {
      "countryName": "United Kingdom",
      "legalStatus": ["Legal","Digital assets are legal in the UK. The regulatory framework applicable to them depends on how the asset is classified.<br/>The Financial Services and Markets Bill has also been introduced in Parliament. It would bring stablecoins within the regulatory perimeter of UK Financial regulators. Recent amendments to the Bill include all digital assets generally. If the bill is passed, rules for the promotion and issuance of financial instruments would also apply to digital assets.  <br/>Her Majesty's Treasury (HMT) published a consultation paper on the 'Future financial services regulatory regime for cryptoassets' in February 2023. The CP proposes a holistic regulatory framework for digital assets. The proposed regulatory framework would extend existing financial regulations regarding issuance, promotion, public offers, disclosure, and orderliness of trading venues to DASPs.  The prposed framework would bring digital assets that do not qualify as securities or e-money tokens, known as unregulated tokens, within the regulatory perimeter of financial authorities like the UK Financial Conduct Authority"],
      "classification":["Yes","The Financial Conduct Authority clarified the regulation of digital assets through Policy Statement 19/22 in 2019. The statement classified digital assets into: <br/>a) security tokens <br/>b) e-money tokens (including stablecoins)<br/>c) unregulated tokens <br>This classification is meant to provide clarity on the regulatory perimeter for digital assets. Security and e-money tokens are within the FCA's jurisdiction whereas unregulated tokens are not. "],
      "licensing": ["Yes","DASPs that offer security tokens or e-money tokens fall within the FCA's jurisdiction and would need the relevant permissions and authorisation. <br/>However, there is no license for DASPs dealing only with unregulated tokens. The HMT's proposed framework (contained in its Consultation Paper) would extend authorisation and license requirements to DASPs even if they offer only unregulated tokens.  <br/>All DASPs must register with the FCA for AML/CFT purposes (covered later) "],
      "corporateGovernance": ["Partial","The FCA prescribes corporate governance for regulated firms, including regular audits, disclosures and statements. <br/>These only apply where a DASP offers a product regulated by the FCA (security or e-money token) and does not apply to unregulated tokens  <br/>If recommendations included in the HMT's consultation paper are accepted, DASPs would be subject to governance requirements that include the resolution of conflicts of interest and transparency. "],
      "riskManagement": ["Partial","DASPs that are under the FCA's jurisdiction must assess and mitigate against risks posed by digital assets as they would for other regulated assets. This includes putting in place relevant protection for client funds.  <br/>There are no reserve or risk management requirements for DASPs outside FCA's jurisdiction.<br/>However, the acceptance of the framework proposed by the HMT would require DASPs, including trading venues and custody services, to adopt prudential requirements including minimum capital and liquidity thresholds to address potential harms from on-going operations. <br/>Additional custody and safeguarding rules will be made applicable to 'cryptoasset custody services'"],
      "taxation":["Yes","Capital Gains and Income Tax on Individuals. <br/>Capital Gains Tax (CGT), Corporation Tax (CT), Corporation Tax on Chargeable Gains (CTCG), Income Tax (IT), Stamp Taxes and VAT for businesses."],
      "capitalControls":["No","The UK does not have a capital controls regime  "],
      "amlCft":["Yes","The Money Laundering, Terrorist Financing, and Transfer of Funds Regulations 2017 are applicable to DASPs.  <br/>The activities that come under the regulatory perimeter are digital asset exchange providers, digital assets ATMs, digital asset issuers and custodian wallet providers. <br/>The entities must undertake KYC requirements and monitor and report suspicious transactions through Suspicious Activity Reports.<br/>The FCA has also issued guidance on how digital asset exchange and custodian wallet providers can comply with AML/CFT requirements. The guidance specifically lists factors that DASPs should consider as high-risk when from an AML/CFT perspective. It specifies that digital assets that provide privacy-enhancing features or products and services that obfuscate transactions should be considered high risk. <br/>While the FCA has not banned any specific digital assets, certain DASPs, such as Kraken have stoped offering privacy coins like Monero. "],
      "grievanceRedressal":["Partial - General Legislation", "The Consumer Rights Act 2015 may apply to businesses that provide services and products to consumers, including DASPs. <br/>However, there are no specific requirements for consumer protection. <br/>The HMT's proposed regulatory framework for digital assets would require DASPs to comply with consumer protection requirements that include creating adequate procedures for handling consumer complaints"],
      "dataProtection":["Partial - General Legislation","Currently, DASPs may qualify as data controllers or processors under the Data Protection Act, 2018. <br/>There are no other information security or data protection requirements specifically for DASPs. <br/>However, HMT's proposed framework would require DASPs to ensure they have the relevant resources and personnel to ensure operational resilience. It also prescribes the adoption of effective 'cyber security protections' "],
      "advertisingRegulations":["Yes","Ads for digital assets are a “red alert” priority issue for The Advertising Standards Authority (ASA) <br/>When entities are promoting digital assets they must make it expressly clear in the ad that:<br/>1. Digital assets are unregulated in the UK.<br/>2. Digital asset profits may be subject to Capital Gains Tax.<br/>3. The value of investments is variable and can go down as well as up.<br/>HMT's proposed framework would create a detailed framework governing the promotion and offering of digital assets to citizens. This would include informing users of: <br/>1. the features of the digital asset <br/>2. rights and obligations attached to the asset <br/>3. outline of the underlying technology <br/>4. details of the person issuing the token or seeking admission on the trading venue"],
      "consumerAwareness":["Proposed","Increasing consumer awareness was cited as a key area for increased policy action in the Crytpoasset Taskforce Report. <br/>The financial regulators have issued several warnings, advisories and guidances to improve consumer awareness of the risks associated with digital assets "],
      "investorProtection":["No","Digital assets are generally not covered by the Financial Services Compensation Scheme - which provides insurance against the loss of financial holdings"],
      "restrictions":["Yes","The FCA has banned the offering of digital asset derivates to retail users due to their high volatility "],
      "lat": "55.3781",
      "lang": "-3.4360"
    },
    {
      "countryName": "United States(Federal Level)",
      "legalStatus": ["Legal","The use of digital assets for payments, investments, and trading is legal in the USA. While there is no holistic regulatory framework for DASPs, a number of regulatory bodies have issued guidances and undertaken enforcement measures related to digital assets and DASPs. The regulatory institutions involved are: <br/>a) Securities and Exchanges Commission - regulation of digital assets that are classified as securities <br/>b) Commodities Futures Trading Commission - digital asset derivates and margin trading for digital asset products <br/>c) Financial Crime Enforcement Network - compliance of DASPs with AML/CFT obligations<br/>d) Office of Foreign Assets Control - compliance by DASPs with sanctions imposed by the US on individuals and entities <br/>e) Department of Justice - criminal prosecution in cases involving digital asset fraud, insider trading, etc. <br/>f) Office of the Comptroller of Currency and Board of Governors of the Federal Reserve System - prudential treatment of digital asset exposure by banks and other regulated financial institutions<br/>g) Federal Deposit Insurance Corporation <br/>There are currently several legislative proposals dealing with digital asset regulation before the US Congress. However, almost all of these are currently at a preliminary stage of consideration. Regulatory measures suggested in these Bills are not included in this tracker.   <br/>In 2022, the US President issued an executive order on 'Ensuring Responsible Development of Digital Assets'. It outlines a whole-of-government approach towards digital asset regulation. Principles identified in the executive order have been incorporated where relevant. "],
      "classification":["No","The US has not adopted a singular definition or classification of digital assets through legislation or regulation<br/>The Financial Crime Enforcement Network's Guidance on 'virtual currencies' defines them as: <i>'virtual' currency is a medium of exchange that operates like a currency in some environments, but does not have all the attributes of real currency. In particular, virtual currency does not have legal tender status in any jurisdiction.' </i><br/>The Tax Guidance on Digital Assets issued by the IRS classifies them as: <br/><i>'Digital assets are broadly defined as any digital representation of value which is recorded on a cryptographically secured distributed ledger or any similar technology as specified by the Secretary.'</i><br/>The Securities and Exchange Commission (SEC) has also classified certain digital assets as securities based on the Howey Test. DAO tokens, in particular, are considered to be securities. However, there is still little clarity on which digital assets can be considered securities (investment contracts) as per the Howey Test. From the SEC's enforcement actions, it would appear that the following assets and services are securities: <br/>a) digital asset lending products <br/>b) digital asset staking services <br/>c) most digital assets offered through initial coin offerings  <br/>d) stablecoins  <br/>The SEC is also responsible for regulating exchange-traded funds based on digital assets. It has given approvals to ETFs based on digital asset futures contracts but has not allowed spot ETFs based on digital assets. <br/>The Commodity Futures Trading Commission's (CFTC) jurisdiction over digital assets is invoked if the assets constitute a commodity. The CFTC's enforcement actions have focused on the unregistered offering of derivative or margined digital asset products, wash trading, and false and misleading communication related to such offerings. "],
      "licensing": ["Yes","All exchanges and administrators of digital assets must register as a Money Service Business with the FinCen under the Banking Secrecy Act. MSBs must implement mechanisms to counter AML/CFT threats and report transactions to FinCen. <br/>Additionally, DASPs must obtain licenses per the money transmission laws of each State they operate in. The licensing requirements vary across States. Wyoming has exempted providers of 'virtual currency' services from the definition of a money transmitter. <br/>In the State of New York, digital asset businesses have to obain a Bit License from the Department of Financial Services. <br/>If DASPs list assets considered securities, registration as a national exchange, broker-dealer, or alternative trading system with the SEC may be required. The SEC has also proposed a change to the definition of the word 'exchange' under the Exchange Act to include communication protocol systems that make available for trading any type of security. This would include digital asset exchange and DeFi platforms that offer digital assets recognised as securities.<br/>Registration as a commodities exchange may be required where DASPs offer digital asset derivatives or margined products. <br/>The Executive Order states that DASPs that pose increased risks to financial stability should be subject to regulatory and supervisory standards that govern traditional market infrastructures and financial firms in line with the principle of 'same business, same risks, same rules'. "],
      "corporateGovernance": ["Partial","While the 2022 Executive Order does not explicitly identify improving governance and transparency of DASPs as an objective, it refers to the importance of ensuring appropriate controls and accountability for digital assets to promote transparency through governance measures. <br/>The Executive Order also requires the SEC, CFTC, Federal Trade Commission (FTC), and Federal Banking Agencies  to submit a report outlining policy recommendations to protect US consumers, investors and businesses <br/>The SEC has pursued enforcement actions in cases involving insider trading related to digital assets. It maintains that the digital assets in question qualified as securities and the use of sensitive information by a Coinbase employee to benefit relatives constitutes insider trading. "],
      "riskManagement": ["Yes","There are no specific risk management procedures of practices for companies providing crypto services. Where crypto assets offered by the company are services, SEC rules in this regard may apply. One of the objectives of the Presidential Executive Order is to mitigate financial risks to consumers by providing adequate protections for custodial and other arrangements relating to consumer assets and funds. <br/>The SEC has proposed amendments to its custody rule under the Investment Advisers Act of 1940. The amendments propose to reduce the risk of loss of client assets by expanding the type of assets covered to digital assets that qualify as funds or securities. Covered assets will be subject to segregation and insolvency requirements.       "],
      "taxation":["Yes","'Virtual currency' is treated as property for tax purposes and income tax and capital gains for property apply to such assets."],
      "capitalControls":["No","The US does not have a capital controls regime.  "],
      "amlCft":["Yes","FinCen exercises oversight over DASPs for AML/CFT purposes. DASPs must register with FinCen as Money Service Businesses and set up mechanisms for verifying customer identity and reporting suspicious transactions. FinCen has also clarified that AML/CFT requirements extend to tumblers and mixers and other service providers used to obfuscate digital asset transactions. "],
      "grievanceRedressal":["No", "While the Federal Trade Commission and Consumer Financial Protection Board are empowered to protect consumers against unfair and deceptive acts, neither has taken decisive action against DASPs thus far.<br/>No regulations or guidelines on this subject have been issued "],
      "dataProtection":["Yes","The Executive Order states that requisite safeguards should be incorporated to maintain privacy and shield users against arbitrary or unlawful surveillance.<br/>It also highlights the cybersecurity risks associated with digital asset exchanges as a key issue. "],
      "advertisingRegulations":["No","Regulations or guidelines limiting or restricting the advertising of digital assets have not been passed so far. <br/>However, the SEC has sued celebrities for their role in promoting tokens that were actually securities. It has also released an advisory on the risks of celebrity backed ICOs.<br/>The FTC is also investigating advertising practises by leading exchanges. "],
      "consumerAwareness":["Partial","The Executive Order identifies protecting consumers and investors as a key objective but does not specifically allude to the need for increasing consumer awareness of digital assets. <br/>However, US financial regulatory authorities, such as the SEC and FDIC, have issued warnings and guidance to consumers regarding digital assets. "],
      "investorProtection":["No","The Federal Deposit Insurance Corporation has clarified that digital assets are not protected by federal insurance and consumers will bear the full extent of losses "],
      "restrictions":["Yes","While there are no regulations that restrict the sale, purchase, ownership and exchange of digital assets, enforcement actions indicate some restrictions on digital assets exist. The SEC's enforcement against companies raising funds through ICOs and statements from the SEC chairman show that most ICOs are regarded as regulated securities offerings. As such, restrictions that apply to traditional securities offerings and also applicable to digital asset issuance. <br/>Some restrictions also exist at the state level. The State of Wyoming allows decentralised autonomous organisations (DAOs) to be registered as LLCs under its laws. A DAO LLC can either be member-managed or algorithmically managed. The articles of association and smart contract of a DAO LLC must govern <br/>- relations among members <br/>- rights and duties of members <br/>- activities of the DAO and conduct of those activities <br/>- means and conditions for amending the operating agreements <br/>- voting rights of members <br/>An algorithmically-managed DAO can only be formed if the underlying smart contract(s) can be updated, modified, or otherwise upgraded.       "],
      "lat": "37.0902",
      "lang": "-95.7129"
    },
    {
      "countryName": "European Union",
      "legalStatus": ["Legal","Digital assets are not specifically regulated at the moment, though regulations in terms of money laundering and privacy do apply. Anti Money Laundering Directive 5 (AMLD5) was passed in 2018 and brings DASPs in the EU within the ambit of AML/CFT requirements. Member nations have implemented the directive domestically through new legislations or amendments to existing ones. <br/>The proposed Markets in Crypto Assets (MiCA) regulation is likely to be formally adopted into law by European Parliament in 2023. The regulation will provide a holistic framework for digital assets across EU member nations. Currently, member nations have their own regulatory frameworks (see France, Germany and Italy above). The approval of MiCA is expected to harmonise regulation of digital assets across the EU. "],
      "classification":["Proposed","MiCA defines 'crypto-assets' as “a digital representation of value or rights which may be transferred and stored electronically, using distributed ledger technology or similar technology”<br/>It classifies them into the following: <br/>1. Asset Referenced Tokens (ARTs) - maintain stable value by referencing value to other currencies, commodities or cryptoassets [primarily stablecoins] <br/>2. E-Money Tokens (EMTs) - crypto-assets that are issued to be a means of exchange and maintain value in reference to fiat currency <br/>3. Utility Tokens - provide access to a DLT-based good or service <br/>Security tokens are not considered crypto-assets and are subject to a different regulatory regime under MiFID II. NFTs are also excluded from the scope of crypto-assets."],
      "licensing": ["Proposed","All DASPs must obtain authorisation as DASPs and have a seat in the EU. Issuance of tokens by DASPs must be coupled with a white paper. DASPs include exchanges, providers of custody and storage services as well as provision of advice on digital assets. <br/>Issuers of ARTs and EMTs are subject to further regulatory obligations, including prior approval of whitepapers and limits on transactions and trading volumes. These tokens are perceived as posing greater risks to the financial system. "],
      "corporateGovernance": ["Proposed","MiCA establishes a detailed governance framework for CASPS, including: <br/>a) Disclosure and transparency requirements <br/>b) Management of conflicts of interests <br/>c) Winding down plans <br/>d) Board constitution "],
      "riskManagement": ["Proposed","Management bodies of ART and EMT issuers are required to ensure prudential management of reserves, including matching value of issued tokens to reserves.   <br/>Segregation requirements are also proposed. <br/>The whitepaper also must disclose details on the issuer, crypto-asset and associated risks and obligations."],
      "taxation":["No","There is currently no specific tax regulation applicable to crypto-assets.<br/>The ECJ has ruled that VAT is not applicable to Bitcoin profits as it considered the cryptocurrency to be a means of payment.   "],
      "capitalControls":["No",""],
      "amlCft":["Yes","AML Directive 5 brings providers of exchanges between digital assetsl and fiat currencies as well as custodian wallet service providers into the EU's ALM framework.       "],
      "grievanceRedressal":["Proposed", "Competent authorities in each EU jurisdiction are required to set up procedures to allow clients and consumer associations to file complaints before them regarding violations of MiCA by DASPs. "],
      "dataProtection":["Proposed","CASPs will be required to comply with the Digital Operational Resilience Act once MiCA comes into force. <br/>The Act requires regulated entities to create an ICT Risk Management Framework. Key aspects of this include an internal governance and control framework, implementation of measures for protection from and prevention of cyberattacks, outlining KPIs for information security risk management as well as detection, response and recovery plans. "],
      "advertisingRegulations":["Proposed"," MiCA requires all marketing communications relating to an offer of utility tokens to be fair, clear and not misleading. They should also state that a whitepaper has been published and indicate the website. "],
      "consumerAwareness":["No","The proposed regulation does not contain specific provisions on fostering consumer awareness about cryptoassets  "],
      "investorProtection":["No","While official documents do not explicitly discuss this subject, statements from regulators indicate that consumers could lose all their money in crypto - indicating that deposit insurance do not apply "],
      "restrictions":["No","There do not appear to be regulatory restrictions on digital asset activity"],
      "lat": "50.5039",
      "lang": "4.4699"
    }

    
    
 ];


 

  
  var markers = [];

    function updateMarkers(selectedValue) {
      removeMarkers();
      displayLegend(selectedValue);

      for (let i = 0; i < countryData.length; i++) {
        var icon;
        if (
          countryData[i][selectedValue][0] == "Legal" ||
          countryData[i][selectedValue][0] == "Yes"
        ) {
          icon = greenIcon;
  
        } else if (
          countryData[i][selectedValue][0] == "Partial Ban" ||
          countryData[i][selectedValue][0] == "Partial" ||  countryData[i][selectedValue][0] == "Partial - General Legislation" )
      {
          icon = orangeIcon
        } else if (
          countryData[i][selectedValue][0] == "No" ||
          countryData[i][selectedValue][0] == "General Ban" ||
          countryData[i][selectedValue][0] == "Prohibited" 
        ) {
            icon = redIcon
        } else if (countryData[i][selectedValue][0] == "Proposed" || countryData[i][selectedValue][0] == "Under Consultation") {
          icon = yellowIcon
        }
        markers.push(
            L.marker([countryData[i].lat, countryData[i].lang], {
              icon: icon,
            })
              .addTo(map)
              .bindTooltip(`${countryData[i].countryName}`)
              .on("click", function () {
                openPopup(countryData[i],selectedValue);
              })
          );
      }
    }

  // Remove Markers Function
  function removeMarkers() {
    for (let i = 0; i < markers.length; i++) {
      map.removeLayer(markers[i]);
    }
  }


  
